const bcrypt = require('bcrypt');
const data = {
    users: [
        {
            name: "Thangadmin",
            email: "admin@example.com",
            // password: bcrypt.hash("123456", 12),
            password: "$2b$12$43Fvr7FTIh30x7naBikq3u/ZOh9Cz43sweuEQcJoMjNThjNbfb0Wi",
            isAdmin: true,
            // isSeller: true,
            // seller: {
            //     name: "Puma",
            //     logo: "/images/logo1.png",
            //     description: "best seller",
            //     rating: 4.5,
            //     numReviews: 120,
            // },
        },
        {
            name: "Thanguser",
            email: "user@example.com",
            // password: bcrypt.hash("123456", 12),
            password: "$2b$12$43Fvr7FTIh30x7naBikq3u/ZOh9Cz43sweuEQcJoMjNThjNbfb0Wi",
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image1: '/assets/images/productImage/p1.jpg',
            image2: '/assets/images/productImage/p2.jpg',
            image3: '/assets/images/productImage/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image1: '/assets/images/productImage/p2.jpg',
            image2: '/assets/images/productImage/p2.jpg',
            image3: '/assets/images/productImage/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image1: '/assets/images/productImage/p3.jpg',
            image2: '/assets/images/productImage/p3.jpg',
            image3: '/assets/images/productImage/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            name: 'Nike Slim Pant',
            category: 'Pants',
            image1: '/assets/images/productImage/p4.jpg',
            image2: '/assets/images/productImage/p4.jpg',
            image3: '/assets/images/productImage/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Puma Slim Pant',
            category: 'Pants',
            image1: '/assets/images/productImage/p5.jpg',
            image2: '/assets/images/productImage/p5.jpg',
            image3: '/assets/images/productImage/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant6',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant1',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant2',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant3',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
module.exports = {
    data
}
