export const ORDER_ROLLBACK_CREATE_REQUEST = 'ORDER_ROLLBACK_CREATE_REQUEST';
export const ORDER_ROLLBACK_CREATE_SUCCESS = 'ORDER_ROLLBACK_CREATE_SUCCESS';
export const ORDER_ROLLBACK_CREATE_FAIL = 'ORDER_ROLLBACK_CREATE_FAIL';
export const ORDER_ROLLBACK_CREATE_RESET = 'ORDER_ROLLBACK_CREATE_RESET';
