export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS_SEND_MAIL = "USER_REGISTER_SUCCESS_SEND_MAIL";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_FIRSTLOGIN = "USER_SIGNIN_FIRSTLOGIN";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";
export const USER_SIGNOUT = "USER_SIGNOUT";
// export const USER_REGISTER_SIGNOUT = 'USER_REGISTER_SIGNOUT';